- name: Ensure /etc/hosts contains required entries
  hosts: servers
  become: true
  tasks:
    - name: Add entries to /etc/hosts if missing
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
        state: present
        regexp: "^{{ item.split(' ')[0] }}\\s"
      loop:
        - "192.168.1.10 server1 server1.example.com #added by ansible"
        - "192.168.1.11 server2 server2.example.com #added by ansible"
        - "192.168.1.12 server3 server3.example.com #added by ansible"
